//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unify.AzureFunctionAppTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unify.AzureFunctionAppTools.ToolResources", typeof(ToolResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during body read..
        /// </summary>
        internal static string ContextCreateBodyReadErrorMessage {
            get {
                return ResourceManager.GetString("ContextCreateBodyReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during body parsing..
        /// </summary>
        internal static string ContextCreateBodyReadParseMessage {
            get {
                return ResourceManager.GetString("ContextCreateBodyReadParseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during body validation..
        /// </summary>
        internal static string ContextCreateBodyValidationErrorMessage {
            get {
                return ResourceManager.GetString("ContextCreateBodyValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request context created with &apos;{0}&apos; status.
        /// </summary>
        internal static string ContextCreateCompleteMessage {
            get {
                return ResourceManager.GetString("ContextCreateCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during header validation..
        /// </summary>
        internal static string ContextCreateHeaderValidationErrorMessage {
            get {
                return ResourceManager.GetString("ContextCreateHeaderValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request context creation aborted due to recieving a preprocessor halt signal..
        /// </summary>
        internal static string ContextCreatePreprocessorHaltMessage {
            get {
                return ResourceManager.GetString("ContextCreatePreprocessorHaltMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during query parameter validation..
        /// </summary>
        internal static string ContextCreateQueryParamValidationErrorMessage {
            get {
                return ResourceManager.GetString("ContextCreateQueryParamValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null preprocessor result from &apos;{0}&apos;..
        /// </summary>
        internal static string NullPreprocessorResultMessage {
            get {
                return ResourceManager.GetString("NullPreprocessorResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor error in &apos;{0}&apos;..
        /// </summary>
        internal static string PreprocessorErrorMessage {
            get {
                return ResourceManager.GetString("PreprocessorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error occured during {0}. It was caught and converted using the configured unhandled error factory..
        /// </summary>
        internal static string UnhandledErrorWarningMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorWarningMessage", resourceCulture);
            }
        }
    }
}
